const data = {
    products: [
        {
            _id:1,
            name:'Consverse Sneaker',
            category:'Sneaker',
            image:'/img/pic-1.jpg',
            price:140,
            brand:'Coverse',
            rating:3.5,
            numReviews:10,
            decription:'medium quality product',
        },
        {
            _id:2,
            name:'ZX 800 W SUPEREARTH',
            category:'Sneaker',
            image:'/img/pic-2.jpg',
            price:170,
            brand:'Adidas',
            rating:4.5,
            numReviews:10,
            decription:'high quality product',
        },
        {
            _id:3,
            name:'X9000 L4',
            category:'Sneaker',
            image:'/img/pic-3.png',
            price:175,
            brand:'Adidas',
            rating:5,
            numReviews:12,
            decription:'high quality product',
        }, 
        {
            _id:4,
            name:'ULTRABOOST 5 DNA',
            category:'Sneaker',
            image:'/img/pic-4.jpg',
            price:200,
            brand:'Adidas',
            rating:5,
            numReviews:30,
            decription:'high quality product',
        },
    ],
};
export default data;